### ISSUE TITLE
Feature request: override server host

### ISSUE THREAD

**Issue by Alphakilo** [mpolden/echoip#109]
In my case the listening IP != the server host. I'm running echoip behind an reverse proxy. In order to have the correct (read: copy/pastable 😄) examples on the HTML output I need to change the index.html template on every update.

I'd like to propose a new parameter, say `-h`, that when used overrides `r.Host` [here](https://github.com/mpolden/echoip/blob/d6d43228858ad0b87b73c0cffd6041ab6445f69d/http/http.go#L343).

This is what I've gotten so far, stuck on what will probably amount to a misunderstanding of Golang 😅: 
https://github.com/Alphakilo/echoip/commit/9e36d4751e55569235e8679fb5df0e9f84ea6aed#r42664811

**Comment by maximbaz** [comment]
Hi, could you please provide some more details about your use-case? Many of us run `echoip` behind a reverse proxy, myself included. On the reverse proxy you map a domain name (say `ifconfig.co`) to the echoip instance, right, so that the requests arriving at `https://ifconfig.co` get forwarded to the echoip instance. If you do just that, the host will be correct.

Could you help me understand what you do differently? Maybe paste some specific config examples, to help clarify what's going on?

**Comment by Alphakilo** [comment]
Hi @maximbaz, thanks for taking time to respond.

This is my NGINX config:
```conf
server {
    listen 80;
    listen [::]:80;

    server_name ip.mydomain.tld;

    location / {
        proxy_pass http://127.0.0.1:8080;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ip.mydomain.tld;

    ssl_certificate /redacted/;
    ssl_certificate_key /redacted/;

    include snippets/tls-moz-modern.conf;

    location / {
        proxy_pass http://127.0.0.1:8080;
    }

}
```

**Comment by Alphakilo** [comment]
Oh nevermind. I was missing `proxy_set_header Host $host;` in the `location`!

**Comment by maximbaz** [comment]
Good catch! Besides that, I think you would also usually add `proxy_set_header X-Forwarded-For $remote_addr;`, just double-check if you need it.

**Comment by Alphakilo** [comment]
I've omited an include in which that line resides ;)
