### ISSUE TITLE
Cannot query the country of the specified IP！

### ISSUE THREAD

**Issue by rong280** [mpolden/echoip#122]
[root@centos8 ~]# curl http://ip.gs/?ip=165.227.166.000/country
Internal server error

**Comment by maximbaz** [comment]
you cannot put query params in between of URL, try `curl 'http://ip.gs/country?ip=165.227.166.000'`

@mpolden since this is not the first time this comes up, I think this should somehow be better documented.

@rong280 could you share where you looked while constructing your curl command, so we make sure to adjust it?

**Comment by rong280** [comment]
> 您不能将查询参数放在URL之间，请尝试 `curl 'http://ip.gs/country?ip=165.227.166.000'`
> 
> @mpolden，因为这不是第一次出现，我认为应该以某种方式更好地记录下来。
> 
> @ rong280您可以在构造curl命令时分享您的外观，所以我们确保对其进行调整？

Thank you very much for your answer

**Comment by mpolden** [comment]
86b68bdf55d41a07f0b2c91e1bb9fbea6f2e9e22 should improve things.
